<?php
if (!defined('TYPO3_MODE')) {
	die ('Access denied.');
}

// --- Get extension configuration ---
$extConf = array();
if ( strlen($_EXTCONF) ) {
	$extConf = unserialize($_EXTCONF);
}

// --- Add static typoscript configurations
//
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($_EXTKEY, 'Configuration/TypoScript/core', 'bootstrap Core');
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($_EXTKEY, 'Configuration/TypoScript/core/multilang', 'bstrap: Multilang');


// --- Set custom flexform for tt_content ctype table
//
$GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds']['*,table'] = 'FILE:EXT:bootstrap_core/Configuration/FlexForm/css_styled_content/flexform_ds.xml';


// --- Add column for icon to tt_content table
//
if ( isset($extConf['enableFontIcons']) && $extConf['enableFontIcons'] == 1 ) {
	// define field
	$tempColumn = array(
		'tx_bootstrapcore_icon' => array (
			'exclude' => 0,
			'label' => 'LLL:EXT:bootstrap_core/Resources/Private/Language/locallang_db.xlf:tt_content.tx_bootstrapcore_icon',
			'config' => array (
				'type' => 'select',
				'default' => '0',
				'size' => 1,
				'maxitems' => 1,
				'items' => array(
					array('', '0'),
					array('Web Application', '--div--'),
						array('Adjust', 'icon-adjust', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-adjust.png'),
						array('Anchor', 'icon-anchor', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-anchor.png'),
						array('Archive', 'icon-archive', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-archive.png'),
						array('Asterisk', 'icon-asterisk', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-asterisk.png'),
						array('Ban circle', 'icon-ban-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ban-circle.png'),
						array('Bar chart', 'icon-bar-chart', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bar-chart.png'),
						array('Barcode', 'icon-barcode', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-barcode.png'),
						array('Beaker', 'icon-beaker', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-beaker.png'),
						array('Beer', 'icon-beer', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-beer.png'),
						array('Bell', 'icon-bell', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bell.png'),
						array('Bell 2', 'icon-bell-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bell-alt.png'),
						array('Bolt', 'icon-bolt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bolt.png'),
						array('Book', 'icon-book', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-book.png'),
						array('Bookmark', 'icon-bookmark', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bookmark.png'),
						array('Bookmark empty', 'icon-bookmark-empty', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bookmark-empty.png'),
						array('Briefcase', 'icon-briefcase', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-briefcase.png'),
						array('Bug', 'icon-bug', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bug.png'),
						array('Building', 'icon-building', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-building.png'),
						array('Bullhorn', 'icon-bullhorn', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bullhorn.png'),
						array('Bullseye', 'icon-bullseye', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bullseye.png'),
						array('Calendar', 'icon-calendar', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-calendar.png'),
						array('Calendar empty', 'icon-calendar-empty', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-calendar-empty.png'),
						array('Camera', 'icon-camera', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-camera.png'),
						array('Camera-retro', 'icon-camera-retro', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-camera-retro.png'),
						array('Certificate', 'icon-certificate', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-certificate.png'),
						array('Check', 'icon-check', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check.png'),
						array('Check empty', 'icon-check-empty', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check-empty.png'),
						array('Check minus', 'icon-check-minus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check-minus.png'),
						array('Check sign', 'icon-check-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check-sign.png'),
						array('Circle', 'icon-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-circle.png'),
						array('Circle blank', 'icon-circle-blank', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-circle-blank.png'),
						array('Cloud', 'icon-cloud', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cloud.png'),
						array('Cloud download', 'icon-cloud-download', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cloud-download.png'),
						array('Cloud upload', 'icon-cloud-upload', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cloud-upload.png'),
						array('Code', 'icon-code', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-code.png'),
						array('Code fork', 'icon-code-fork', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-code-fork.png'),
						array('Coffee', 'icon-coffee', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-coffee.png'),
						array('Cog', 'icon-cog', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cog.png'),
						array('Cogs', 'icon-cogs', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cogs.png'),
						array('Collapse', 'icon-collapse', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-collapse.png'),
						array('Collapse 2', 'icon-collapse-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-collapse-alt.png'),
						array('Collapse top', 'icon-collapse-top', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-collapse-top.png'),
						array('Comment', 'icon-comment', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comment.png'),
						array('Comment 2', 'icon-comment-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comment-alt.png'),
						array('Comments', 'icon-comments', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comments.png'),
						array('Comments 2', 'icon-comments-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comments-alt.png'),
						array('Compass', 'icon-compass', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-compass.png'),
						array('Credit card', 'icon-credit-card', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-credit-card.png'),
						array('Crop', 'icon-crop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-crop.png'),
						array('Dashboard', 'icon-dashboard', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-dashboard.png'),
						array('Desktop', 'icon-desktop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-desktop.png'),
						array('Download', 'icon-download', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-download.png'),
						array('Download 2', 'icon-download-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-download-alt.png'),
						array('Edit', 'icon-edit', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-edit.png'),
						array('Edit sign', 'icon-edit-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-edit-sign.png'),
						array('Ellipsis horizontal', 'icon-ellipsis-horizontal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ellipsis-horizontal.png'),
						array('Ellipsis vertical', 'icon-ellipsis-vertical', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ellipsis-vertical.png'),
						array('Envelope', 'icon-envelope', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-envelope.png'),
						array('Envelope-alt', 'icon-envelope-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-envelope-alt.png'),
						array('Eraser', 'icon-eraser', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eraser.png'),
						array('Exchange', 'icon-exchange', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-exchange.png'),
						array('Exclamation', 'icon-exclamation', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-exclamation.png'),
						array('Exclamation sign', 'icon-exclamation-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-exclamation-sign.png'),
						array('Expand', 'icon-expand', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-expand.png'),
						array('Expand-alt', 'icon-expand-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-expand-alt.png'),
						array('External link', 'icon-external-link', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-external-link.png'),
						array('External link sign', 'icon-external-link-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-external-link-sign.png'),
						array('Eye close', 'icon-eye-close', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eye-close.png'),
						array('Eye open', 'icon-eye-open', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eye-open.png'),
						array('Facetime video', 'icon-facetime-video', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-facetime-video.png'),
						array('Female', 'icon-female', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-female.png'),
						array('Fighter jet', 'icon-fighter-jet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fighter-jet.png'),
						array('Film', 'icon-film', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-film.png'),
						array('Filter', 'icon-filter', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-filter.png'),
						array('Fire', 'icon-fire', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fire.png'),
						array('Fire extinguisher', 'icon-fire-extinguisher', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fire-extinguisher.png'),
						array('Flag', 'icon-flag', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flag.png'),
						array('Flag 2', 'icon-flag-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flag-alt.png'),
						array('Flag', 'icon-flag-checkered', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flag-checkered.png'),
						array('Folder close', 'icon-folder-close', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder-close.png'),
						array('Folder close 2', 'icon-folder-close-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder-close-alt.png'),
						array('Folder open', 'icon-folder-open', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder-open.png'),
						array('Folder open 2', 'icon-folder-open-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder-open-alt.png'),
						array('Food', 'icon-food', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-food.png'),
						array('Frown', 'icon-frown', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-frown.png'),
						array('Gamepad', 'icon-gamepad', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gamepad.png'),
						array('Gift', 'icon-gift', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gift.png'),
						array('Glass', 'icon-glass', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-glass.png'),
						array('Globe', 'icon-globe', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-globe.png'),
						array('Group', 'icon-group', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-group.png'),
						array('HDD', 'icon-hdd', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hdd.png'),
						array('Headphones', 'icon-headphones', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-headphones.png'),
						array('Heart', 'icon-heart', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-heart.png'),
						array('Heart empty', 'icon-heart-empty', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-heart-empty.png'),
						array('Home', 'icon-home', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-home.png'),
						array('Inbox', 'icon-inbox', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-inbox.png'),
						array('Info', 'icon-info', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-info.png'),
						array('Info sign', 'icon-info-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-info-sign.png'),
						array('Key', 'icon-key', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-key.png'),
						array('Keyboard', 'icon-keyboard', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-keyboard.png'),
						array('Laptop', 'icon-laptop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-laptop.png'),
						array('Leaf', 'icon-leaf', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-leaf.png'),
						array('Legal', 'icon-legal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-legal.png'),
						array('Lemon', 'icon-lemon', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-lemon.png'),
						array('Level down', 'icon-level-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-level-down.png'),
						array('Level up', 'icon-level-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-level-up.png'),
						array('Lightbulb', 'icon-lightbulb', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-lightbulb.png'),
						array('Location arrow', 'icon-location-arrow', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-location-arrow.png'),
						array('Lock', 'icon-lock', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-lock.png'),
						array('Magic', 'icon-magic', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-magic.png'),
						array('Magnet', 'icon-magnet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-magnet.png'),
						array('Mail reply all', 'icon-mail-reply-all', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-mail-reply-all.png'),
						array('Male', 'icon-male', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-male.png'),
						array('Map marker', 'icon-map-marker', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-map-marker.png'),
						array('Meh', 'icon-meh', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-meh.png'),
						array('Microphone', 'icon-microphone', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-microphone.png'),
						array('Microphone off', 'icon-microphone-off', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-microphone-off.png'),
						array('Minus', 'icon-minus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-minus.png'),
						array('Minus sign', 'icon-minus-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-minus-sign.png'),
						array('Minus sign 2', 'icon-minus-sign-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-minus-sign-alt.png'),
						array('Mobile phone', 'icon-mobile-phone', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-mobile-phone.png'),
						array('Money', 'icon-money', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-money.png'),
						array('Moon', 'icon-moon', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-moon.png'),
						array('Move', 'icon-move', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-move.png'),
						array('Music', 'icon-music', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-music.png'),
						array('Off', 'icon-off', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-off.png'),
						array('Ok', 'icon-ok', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ok.png'),
						array('Ok circle', 'icon-ok-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ok-circle.png'),
						array('Ok sign', 'icon-ok-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ok-sign.png'),
						array('Pencil', 'icon-pencil', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pencil.png'),
						array('Phone', 'icon-phone', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-phone.png'),
						array('Phone sign', 'icon-phone-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-phone-sign.png'),
						array('Picture', 'icon-picture', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-picture.png'),
						array('Plane', 'icon-plane', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plane.png'),
						array('Plus', 'icon-plus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plus.png'),
						array('Plus sign', 'icon-plus-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plus-sign.png'),
						array('Plus sign 2', 'icon-plus-sign-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plus-sign-alt.png'),
						array('Print', 'icon-print', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-print.png'),
						array('Pushpin', 'icon-pushpin', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pushpin.png'),
						array('Puzzle piece', 'icon-puzzle-piece', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-puzzle-piece.png'),
						array('Qrcode', 'icon-qrcode', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-qrcode.png'),
						array('Question', 'icon-question', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-question.png'),
						array('Question sign', 'icon-question-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-question-sign.png'),
						array('Quote left', 'icon-quote-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-quote-left.png'),
						array('Quote right', 'icon-quote-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-quote-right.png'),
						array('Random', 'icon-random', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-random.png'),
						array('Refresh', 'icon-refresh', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-refresh.png'),
						array('Remove', 'icon-remove', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-remove.png'),
						array('Remove circle', 'icon-remove-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-remove-circle.png'),
						array('Remove sign', 'icon-remove-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-remove-sign.png'),
						array('Reorder', 'icon-reorder', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-reorder.png'),
						array('Reply', 'icon-reply', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-reply.png'),
						array('Reply all', 'icon-reply-all', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-reply-all.png'),
						array('Resize horizontal', 'icon-resize-horizontal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-horizontal.png'),
						array('Resize vertical', 'icon-resize-vertical', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-vertical.png'),
						array('Retweet', 'icon-retweet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-retweet.png'),
						array('Road', 'icon-road', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-road.png'),
						array('Rocket', 'icon-rocket', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-rocket.png'),
						array('RSS', 'icon-rss', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-rss.png'),
						array('RSS sign', 'icon-rss-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-rss-sign.png'),
						array('Screenshot', 'icon-screenshot', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-screenshot.png'),
						array('Search', 'icon-search', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-search.png'),
						array('Share', 'icon-share', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-share.png'),
						array('Share 2', 'icon-share-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-share-alt.png'),
						array('Share sign', 'icon-share-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-share-sign.png'),
						array('Shield', 'icon-shield', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-shield.png'),
						array('Shopping cart', 'icon-shopping-cart', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-shopping-cart.png'),
						array('Sign blank', 'icon-sign-blank', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sign-blank.png'),
						array('Signal', 'icon-signal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-signal.png'),
						array('Signin', 'icon-signin', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-signin.png'),
						array('Signout', 'icon-signout', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-signout.png'),
						array('Sitemap', 'icon-sitemap', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sitemap.png'),
						array('Smile', 'icon-smile', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-smile.png'),
						array('Sort', 'icon-sort', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort.png'),
						array('Sort by alpha', 'icon-sort-by-alphabet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-by-alphabet.png'),
						array('Sort by alpha 2', 'icon-sort-by-alphabet-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-by-alphabet-alt.png'),
						array('Sort by attrib', 'icon-sort-by-attributes', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-by-attributes.png'),
						array(' Sort by attrib 2', 'icon-sort-by-attributes-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-by-attributes-alt.png'),
						array('Sort by order', 'icon-sort-by-order', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-by-order.png'),
						array('Sort by order 2', 'icon-sort-by-order-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-by-order-alt.png'),
						array('Sort down', 'icon-sort-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-down.png'),
						array('Sort up', 'icon-sort-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-up.png'),
						array('Spinner', 'icon-spinner', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-spinner.png'),
						array('Star', 'icon-star', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star.png'),
						array('Star empty', 'icon-star-empty', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star-empty.png'),
						array('Star half', 'icon-star-half', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star-half.png'),
						array('Star half empty', 'icon-star-half-empty', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star-half-empty.png'),
						array('Subscript', 'icon-subscript', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-subscript.png'),
						array('Suitcase', 'icon-suitcase', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-suitcase.png'),
						array('Sun', 'icon-sun', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sun.png'),
						array('Superscript', 'icon-superscript', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-superscript.png'),
						array('Tablet', 'icon-tablet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tablet.png'),
						array('Tag', 'icon-tag', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tag.png'),
						array('Tags', 'icon-tags', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tags.png'),
						array('Tasks', 'icon-tasks', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tasks.png'),
						array('Terminal', 'icon-terminal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-terminal.png'),
						array('Thumbs', 'icon-thumbs-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-down.png'),
						array('Thumbs', 'icon-thumbs-down-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-down-alt.png'),
						array('Thumbs', 'icon-thumbs-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-up.png'),
						array('Thumbs', 'icon-thumbs-up-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-up-alt.png'),
						array('Ticket', 'icon-ticket', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ticket.png'),
						array('Time', 'icon-time', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-time.png'),
						array('Tint', 'icon-tint', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tint.png'),
						array('Trash', 'icon-trash', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-trash.png'),
						array('Trophy', 'icon-trophy', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-trophy.png'),
						array('Truck', 'icon-truck', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-truck.png'),
						array('Umbrella', 'icon-umbrella', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-umbrella.png'),
						array('Unlock', 'icon-unlock', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-unlock.png'),
						array('Unlock 2', 'icon-unlock-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-unlock-alt.png'),
						array('Upload', 'icon-upload', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-upload.png'),
						array('Upload 2', 'icon-upload-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-upload-alt.png'),
						array('User', 'icon-user', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-user.png'),
						array('Volume down', 'icon-volume-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-volume-down.png'),
						array('Volume off', 'icon-volume-off', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-volume-off.png'),
						array('Volume up', 'icon-volume-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-volume-up.png'),
						array('Warning sign', 'icon-warning-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-warning-sign.png'),
						array('Wrench', 'icon-wrench', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-wrench.png'),
						array('Zoom in', 'icon-zoom-in', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-zoom-in.png'),
						array('Zoom out', 'icon-zoom-out', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-zoom-out.png'),
					array('Text Editor', '--div--'),
						array('Align center', 'icon-align-center', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-center.png'),
						array('Align justify', 'icon-align-justify', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-justify.png'),
						array('Align left', 'icon-align-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-left.png'),
						array('Align right', 'icon-align-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-right.png'),
						array('Bold', 'icon-bold', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bold.png'),
						array('Columns', 'icon-columns', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-columns.png'),
						array('Copy', 'icon-copy', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-copy.png'),
						array('cut', 'icon-cut', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cut.png'),
						array('Eraser', 'icon-eraser', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eraser.png'),
						array('File', 'icon-file', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file.png'),
						array('File 2', 'icon-file-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file-alt.png'),
						array('File text', 'icon-file-text', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file-text.png'),
						array('File text 2', 'icon-file-text-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file-text-alt.png'),
						array('Font', 'icon-font', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-font.png'),
						array('Indent left', 'icon-indent-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-indent-left.png'),
						array('Indent right', 'icon-indent-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-indent-right.png'),
						array('Italic', 'icon-italic', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-italic.png'),
						array('Link', 'icon-link', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-link.png'),
						array('List', 'icon-list', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list.png'),
						array('List 2', 'icon-list-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list-alt.png'),
						array('Ordered List', 'icon-list-ol', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list-ol.png'),
						array('Unordered List', 'icon-list-ul', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list-ul.png'),
						array('Paper clip', 'icon-paper-clip', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-paper-clip.png'),
						array('Paste', 'icon-paste', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-paste.png'),
						array('Repeat', 'icon-repeat', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-repeat.png'),
						array('Save', 'icon-save', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-save.png'),
						array('Strike through', 'icon-strikethrough', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-strikethrough.png'),
						array('Table', 'icon-table', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-table.png'),
						array('Text height', 'icon-text-height', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-text-height.png'),
						array('Text width', 'icon-text-width', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-text-width.png'),
						array('Table header', 'icon-th', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-th.png'),
						array('Table header large', 'icon-th-large', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-th-large.png'),
						array('Table header list', 'icon-th-list', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-th-list.png'),
						array('Underline', 'icon-underline', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-underline.png'),
						array('Undo', 'icon-undo', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-undo.png'),
						array('Unlink', 'icon-unlink', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-unlink.png'),
					array('Directional', '--div--'),
						array('Angle down', 'icon-angle-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-down.png'),
						array('Angle left', 'icon-angle-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-left.png'),
						array('Angle right', 'icon-angle-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-right.png'),
						array('Angle up', 'icon-angle-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-up.png'),
						array('Arrow down', 'icon-arrow-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-down.png'),
						array('Arrow left', 'icon-arrow-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-left.png'),
						array('Arrow right', 'icon-arrow-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-right.png'),
						array('Arrow up', 'icon-arrow-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-up.png'),
						array('Caret down', 'icon-caret-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-down.png'),
						array('Caret left', 'icon-caret-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-left.png'),
						array('Caret right', 'icon-caret-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-right.png'),
						array('Caret up', 'icon-caret-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-up.png'),
						array('Chevron down', 'icon-chevron-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-down.png'),
						array('Chevron left', 'icon-chevron-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-left.png'),
						array('Chevron right', 'icon-chevron-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-right.png'),
						array('Chevron sign down', 'icon-chevron-sign-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-sign-down.png'),
						array('Chevron sign left', 'icon-chevron-sign-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-sign-left.png'),
						array('Chevron sign right', 'icon-chevron-sign-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-sign-right.png'),
						array('Chevron sign up', 'icon-chevron-sign-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-sign-up.png'),
						array('Chevron up', 'icon-chevron-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-up.png'),
						array('Circle arrow down', 'icon-circle-arrow-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-circle-arrow-down.png'),
						array('Circle arrow left', 'icon-circle-arrow-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-circle-arrow-left.png'),
						array('Circle arrow right', 'icon-circle-arrow-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-circle-arrow-right.png'),
						array('Circle arrow up', 'icon-circle-arrow-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-circle-arrow-up.png'),
						array('Double angle down', 'icon-double-angle-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-double-angle-down.png'),
						array('Double angle left', 'icon-double-angle-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-double-angle-left.png'),
						array('Double angle right', 'icon-double-angle-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-double-angle-right.png'),
						array('Double angle up', 'icon-double-angle-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-double-angle-up.png'),
						array('Hand down', 'icon-hand-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-down.png'),
						array('Hand left', 'icon-hand-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-left.png'),
						array('Hand right', 'icon-hand-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-right.png'),
						array('Hand up', 'icon-hand-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-up.png'),
						array('Long arrow down', 'icon-long-arrow-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-down.png'),
						array('Long arrow left', 'icon-long-arrow-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-left.png'),
						array('Long arrow right', 'icon-long-arrow-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-right.png'),
						array('Long arrow up', 'icon-long-arrow-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-up.png'),
					array('Video Player', '--div--'),
						array('Backwards', 'icon-backward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-backward.png'),
						array('Eject', 'icon-eject', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eject.png'),
						array('Fast backwards', 'icon-fast-backward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fast-backward.png'),
						array('Fast forward', 'icon-fast-forward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fast-forward.png'),
						array('Forward', 'icon-forward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-forward.png'),
						array('Fullscreen', 'icon-fullscreen', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fullscreen.png'),
						array('Pause', 'icon-pause', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pause.png'),
						array('Play', 'icon-play', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-play.png'),
						array('Play (circle)', 'icon-play-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-play-circle.png'),
						array('Play (sign)', 'icon-play-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-play-sign.png'),
						array('Resize full', 'icon-resize-full', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-full.png'),
						array('Resize small', 'icon-resize-small', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-small.png'),
						array('Step backward', 'icon-step-backward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-step-backward.png'),
						array('Step forward', 'icon-step-forward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-step-forward.png'),
						array('Stop', 'icon-stop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-stop.png'),
						array('Youtube play', 'icon-youtube-play', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube-play.png'),
					array('Currencies', '--div--'),
						array('Euro', 'icon-eur', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eur.png'),
						array('US Dollar', 'icon-usd', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-usd.png'),
						array('UK Pounds', 'icon-gbp', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gbp.png'),
						array('Japan Yen', 'icon-jpy', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-jpy.png'),
						array('Chinese Reminbi', 'icon-cny', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cny.png'),
						array('India Rubee', 'icon-inr', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-inr.png'),
						array('Korea Won', 'icon-krw', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-krw.png'),
						array('Bitcoin', 'icon-btc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-btc.png'),
					array('Brand', '--div--'),
						array('Adn', 'icon-adn', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-adn.png'),
						array('Android', 'icon-android', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-android.png'),
						array('Apple', 'icon-apple', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-apple.png'),
						array('Bitbucket', 'icon-bitbucket', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bitbucket.png'),
						array('Bitbucket sign', 'icon-bitbucket-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bitbucket-sign.png'),
						array('CSS3', 'icon-css3', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-css3.png'),
						array('Dribble', 'icon-dribbble', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-dribbble.png'),
						array('Dropbox', 'icon-dropbox', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-dropbox.png'),
						array('Facebook', 'icon-facebook', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-facebook.png'),
						array('Facebook sign', 'icon-facebook-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-facebook-sign.png'),
						array('Flickr', 'icon-flickr', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flickr.png'),
						array('Foursquare', 'icon-foursquare', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-foursquare.png'),
						array('Github', 'icon-github', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-github.png'),
						array('Github 2', 'icon-github-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-github-alt.png'),
						array('Github sign', 'icon-github-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-github-sign.png'),
						array('GitTip', 'icon-gittip', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gittip.png'),
						array('Google+', 'icon-google-plus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-google-plus.png'),
						array('Google+ sign', 'icon-google-plus-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-google-plus-sign.png'),
						array('HTML5', 'icon-html5', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-html5.png'),
						array('Instagram', 'icon-instagram', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-instagram.png'),
						array('LinkedIn', 'icon-linkedin', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-linkedin.png'),
						array('LinkedIn sign', 'icon-linkedin-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-linkedin-sign.png'),
						array('Linux', 'icon-linux', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-linux.png'),
						array('MaxCDN', 'icon-maxcdn', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-maxcdn.png'),
						array('Pinterest', 'icon-pinterest', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pinterest.png'),
						array('Pinterest sign', 'icon-pinterest-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pinterest-sign.png'),
						array('Renren', 'icon-renren'),
						array('Skype', 'icon-skype', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-skype.png'),
						array('StackExchange', 'icon-stackexchange', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-stackexchange.png'),
						array('Trello', 'icon-trello', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-trello.png'),
						array('Tumblr', 'icon-tumblr', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tumblr.png'),
						array('Tumblr sign', 'icon-tumblr-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tumblr-sign.png'),
						array('Twitter', 'icon-twitter', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-twitter.png'),
						array('Twitter sign', 'icon-twitter-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-twitter-sign.png'),
						array('VK', 'icon-vk', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-vk.png'),
						array('Weibo', 'icon-weibo', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-weibo.png'),
						array('Windows', 'icon-windows', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-windows.png'),
						array('Xing', 'icon-xing', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-xing.png'),
						array('Xing sign', 'icon-xing-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-xing-sign.png'),
						array('YouTube', 'icon-youtube', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube.png'),
						array('YouTube play', 'icon-youtube-play', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube-play.png'),
						array('YouTube sign', 'icon-youtube-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube-sign.png'),
					array('Medical', '--div--'),
						array('Ambulance', 'icon-ambulance', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ambulance.png'),
						array('H-Sign', 'icon-h-sign', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-h-sign.png'),
						array('Hospital', 'icon-hospital', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hospital.png'),
						array('MedKit', 'icon-medkit', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-medkit.png'),
						array('Stethoscope', 'icon-stethoscope', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-stethoscope.png'),
						array('User MD', 'icon-user-md', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-user-md.png')
				)
			)
		)
	);

	// Add field to tt_content
	//
	if ( isset($extConf['showFontIconsOnSeparateTab']) && $extConf['showFontIconsOnSeparateTab'] == 1 ) {
		// change label (info that icon is for header)
		$tempColumn['tx_bootstrapcore_icon']['label'] = 'LLL:EXT:bootstrap_core/Resources/Private/Language/locallang_db.xlf:tt_content.tx_bootstrapcore_iconbeforeheader';
		// show 30 cols of icons (below selectbox)
		$tempColumn['tx_bootstrapcore_icon']['config']['selicon_cols'] = '30';
		// add on extended tab
		\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns('tt_content', $tempColumn, 1);
		\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes('tt_content', 'tx_bootstrapcore_icon', '', 'before:tx_gridelements_container');
	} else {
		// show icons in select options
		$tempColumn['tx_bootstrapcore_icon']['config']['iconsInOptionTags'] = 1;
		// don't show icons below select box
		$tempColumn['tx_bootstrapcore_icon']['config']['suppress_icons'] = 'ONLY_SELECTED';
		// add after header_layout
		\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns('tt_content', $tempColumn, 1);
		\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addFieldsToPalette('tt_content', 'header', 'tx_bootstrapcore_icon', 'after:header_layout');
	}

	// Add static ts configurations for FontAwesome
	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($_EXTKEY, 'Configuration/TypoScript/lib/fontawesome', 'bstrap: FontAwesome');
}



// --- Change imagewidth to a select field
//
// only if enabled in extension configuration
if ( isset($extConf['enableModifiedImageRendering']) && $extConf['enableModifiedImageRendering'] == 1 ) {

	// define field
	$tempColumn = array(
		'tx_bootstrapcore_imageswidth' => array (
			'exclude' => 0,
			'label' => 'LLL:EXT:bootstrap_core/Resources/Private/Language/locallang_db.xlf:tt_content.tx_bootstrapcore_imageswidth',
			'config' => array (
				'type' => 'select',
				'items' => array(
					array('LLL:EXT:bootstrap_core/Resources/Private/Language/locallang_db.xlf:tt_content.tx_bootstrapcore_imageswidth.I.0', '0'),
					array('1/12',   '1'),
					array('2/12',  '2'),
					array('25%',   '3'),
					array('33%',   '4'),
					array('5/12',  '5'),
					array('50%',   '6'),
					array('7/12',  '7'),
					array('66%',   '8'),
					array('75%',   '9'),
					array('10/12', '10'),
					array('11/12', '11'),
					array('100%',  '12')
				),
				'size' => 1,
				'maxitems' => 1,
			)
		)
	);
	// Add field to tt_content, in form before imagewidth
	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns('tt_content', $tempColumn, 1);
	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addFieldsToPalette('tt_content', 'image_settings', 'tx_bootstrapcore_imageswidth', 'before:imagewidth');

	// Add static ts configurations for responsive image rendering
	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($_EXTKEY, 'Configuration/TypoScript/core/tt_content/image/responsive', 'bstrap: Responsive Images');
}



// --- Add more static ts configurations (extensions, libs)
//
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($_EXTKEY, 'Configuration/TypoScript/ext/indexed_search', 'bstrap: Indexed Search');
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($_EXTKEY, 'Configuration/TypoScript/ext/felogin', 'bstrap: FE Login');
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($_EXTKEY, 'Configuration/TypoScript/lib/googleanalytics', 'bstrap: Google Analytics');

?>