<?php

// Font Awesome Icons v3.2.1
//
$iconFontOption = array(array('', '0'),
						array('Web Application', '--div--'),
							array('Adjust', 'fa-adjust', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-adjust.png'),
							array('Anchor', 'fa-anchor', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-anchor.png'),
							array('Archive', 'fa-archive', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-archive.png'),
							array('Arrow circle down', 'fa-arrow-circle-o-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-o-down.png'),
							array('Asterisk', 'fa-asterisk', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-asterisk.png'),
							array('Ban circle', 'fa-ban', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ban.png'),
							array('Bar chart', 'fa-bar-chart-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bar-chart-o.png'),
							array('Barcode', 'fa-barcode', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-barcode.png'),
							array('Beaker', 'fa-flask', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flask.png'),
							array('Beer', 'fa-beer', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-beer.png'),
							array('Bell', 'fa-bell-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bell-o.png'),
							array('Bell 2', 'fa-bell', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bell.png'),
							array('Bolt', 'fa-bolt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bolt.png'),
							array('Book', 'fa-book', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-book.png'),
							array('Bookmark', 'fa-bookmark', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bookmark.png'),
							array('Bookmark empty', 'fa-bookmark-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bookmark-o.png'),
							array('Briefcase', 'fa-briefcase', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-briefcase.png'),
							array('Bug', 'fa-bug', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bug.png'),
							array('Building', 'fa-building', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-building.png'),
							array('Bullhorn', 'fa-bullhorn', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bullhorn.png'),
							array('Bullseye', 'fa-bullseye', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bullseye.png'),
							array('Calendar', 'fa-calendar', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-calendar.png'),
							array('Calendar empty', 'fa-calendar-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-calendar-o.png'),
							array('Camera', 'fa-camera', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-camera.png'),
							array('Camera-retro', 'fa-camera-retro', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-camera-retro.png'),
							array('Caret square down', 'fa-caret-square-o-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-square-o-down.png'),
							array('Caret square up', 'fa-caret-square-o-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-square-o-up.png'),
							array('Certificate', 'fa-certificate', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-certificate.png'),
							array('Check', 'fa-check-square-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check-square-o.png'),
							array('Check', 'fa-check', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check.png'),
							array('Check circle', 'fa-check-circle-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check-circle-o.png'),
							array('Check sign', 'fa-check-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check-circle.png'),
							array('Check sign', 'fa-check-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check-square.png'),
							array('Circle', 'fa-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-circle.png'),
							array('Circle blank', 'fa-circle-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-circle-o.png'),
							array('Clock', 'fa-clock-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-clock-o.png'),
							array('Cloud', 'fa-cloud', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cloud.png'),
							array('Cloud download', 'fa-cloud-download', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cloud-download.png'),
							array('Cloud upload', 'fa-cloud-upload', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cloud-upload.png'),
							array('Code', 'fa-code', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-code.png'),
							array('Code fork', 'fa-code-fork', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-code-fork.png'),
							array('Coffee', 'fa-coffee', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-coffee.png'),
							array('Cog', 'fa-cog', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cog.png'),
							array('Cogs', 'fa-cogs', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cogs.png'),
							array('Collapse', 'fa-collapse-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-collapse-o.png'),
							array('Comment', 'fa-comment', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comment.png'),
							array('Comment 2', 'fa-comment-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comment-o.png'),
							array('Comments', 'fa-comments', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comments.png'),
							array('Comments 2', 'fa-comments-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comments-o.png'),
							array('Compass', 'fa-compass', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-compass.png'),
							array('Credit card', 'fa-credit-card', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-credit-card.png'),
							array('Crop', 'fa-crop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-crop.png'),
							array('Crosshairs', 'fa-crosshairs', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-crosshairs.png'),
							array('Cutlery', 'fa-cutlery', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cutlery.png'),
							array('Desktop', 'fa-desktop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-desktop.png'),
							array('Download', 'fa-download', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-download.png'),
							array('Ellipsis horizontal', 'fa-ellipsis-horizontal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ellipsis-horizontal.png'),
							array('Ellipsis vertical', 'fa-ellipsis-vertical', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ellipsis-vertical.png'),
							array('Envelope', 'fa-envelope', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-envelope.png'),
							array('Envelope-alt', 'fa-envelope-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-envelope-o.png'),
							array('Eraser', 'fa-eraser', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eraser.png'),
							array('Exchange', 'fa-exchange', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-exchange.png'),
							array('Exclamation', 'fa-exclamation', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-exclamation.png'),
							array('Exclamation sign', 'fa-exclamation-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-exclamation-circle.png'),
							array('Exclamation triangle', 'fa-exclamation-triangle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-exclamation-triangle.png'),
							array('Expand', 'fa-caret-square-o-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-square-o-right.png'),
							array('Expand-alt', 'fa-expand-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-expand-o.png'),
							array('External link', 'fa-external-link', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-external-link.png'),
							array('External link sign', 'fa-external-link-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-external-link-square.png'),
							array('Eye close', 'fa-eye-slash', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eye-slash.png'),
							array('Eye', 'fa-eye', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eye.png'),
							array('Female', 'fa-female', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-female.png'),
							array('Fighter jet', 'fa-fighter-jet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fighter-jet.png'),
							array('Film', 'fa-film', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-film.png'),
							array('Filter', 'fa-filter', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-filter.png'),
							array('Fire', 'fa-fire', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fire.png'),
							array('Fire extinguisher', 'fa-fire-extinguisher', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fire-extinguisher.png'),
							array('Flag', 'fa-flag', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flag.png'),
							array('Flag 2', 'fa-flag-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flag-o.png'),
							array('Flag', 'fa-flag-checkered', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flag-checkered.png'),
							array('Folder close', 'fa-folder', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder.png'),
							array('Folder close 2', 'fa-folder-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder-o.png'),
							array('Folder open', 'fa-folder-open', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder-open.png'),
							array('Folder open 2', 'fa-folder-open-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder-open-o.png'),
							array('Frown', 'fa-frown-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-frown-o.png'),
							array('Gamepad', 'fa-gamepad', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gamepad.png'),
							array('Gift', 'fa-gift', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gift.png'),
							array('Glass', 'fa-glass', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-glass.png'),
							array('Globe', 'fa-globe', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-globe.png'),
							array('Group', 'fa-group', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-group.png'),
							array('HDD', 'fa-hdd-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hdd-o.png'),
							array('Headphones', 'fa-headphones', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-headphones.png'),
							array('Heart', 'fa-heart', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-heart.png'),
							array('Heart empty', 'fa-heart-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-heart-o.png'),
							array('Home', 'fa-home', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-home.png'),
							array('Inbox', 'fa-inbox', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-inbox.png'),
							array('Info', 'fa-info', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-info.png'),
							array('Info sign', 'fa-info-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-info-circle.png'),
							array('Key', 'fa-key', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-key.png'),
							array('Keyboard', 'fa-keyboard-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-keyboard-o.png'),
							array('Laptop', 'fa-laptop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-laptop.png'),
							array('Leaf', 'fa-leaf', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-leaf.png'),
							array('Legal', 'fa-gavel', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gavel.png'),
							array('Lemon', 'fa-lemon-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-lemon-o.png'),
							array('Level down', 'fa-level-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-level-down.png'),
							array('Level up', 'fa-level-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-level-up.png'),
							array('Lightbulb', 'fa-lightbulb-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-lightbulb-o.png'),
							array('Location arrow', 'fa-location-arrow', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-location-arrow.png'),
							array('Lock', 'fa-lock', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-lock.png'),
							array('Magic', 'fa-magic', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-magic.png'),
							array('Magnet', 'fa-magnet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-magnet.png'),
							array('Mail reply all', 'fa-mail-reply-all', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-mail-reply-all.png'),
							array('Male', 'fa-male', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-male.png'),
							array('Map marker', 'fa-map-marker', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-map-marker.png'),
							array('Meh', 'fa-meh-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-meh-o.png'),
							array('Microphone', 'fa-microphone', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-microphone.png'),
							array('Microphone slash', 'fa-microphone-slash', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-microphone-slash.png'),
							array('Minus', 'fa-minus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-minus.png'),
							array('Minus square', 'fa-minus-square-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-minus-square-o.png'),
							array('Minus sign', 'fa-minus-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-minus-circle.png'),
							array('Minus sign 2', 'fa-minus-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-minus-square.png'),
							array('Mobile', 'fa-mobile', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-mobile.png'),
							array('Money', 'fa-money', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-money.png'),
							array('Moon', 'fa-moon-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-moon-o.png'),
							array('Move', 'fa-move', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-move.png'),
							array('Music', 'fa-music', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-music.png'),
							array('Pencil', 'fa-pencil', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pencil.png'),
							array('Pencil', 'fa-pencil-square-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pencil-square-o.png'),
							array('Pencil square', 'fa-pencil-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pencil-square.png'),
							array('Phone', 'fa-phone', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-phone.png'),
							array('Phone sign', 'fa-phone-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-phone-square.png'),
							array('Picture', 'fa-picture-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-picture-o.png'),
							array('Plane', 'fa-plane', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plane.png'),
							array('Plus', 'fa-plus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plus.png'),
							array('Plus sign', 'fa-plus-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plus-circle.png'),
							array('Plus sign 2', 'fa-plus-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plus-square.png'),
							array('Power off', 'fa-power-off', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-power-off.png'),
							array('Print', 'fa-print', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-print.png'),
							array('Puzzle piece', 'fa-puzzle-piece', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-puzzle-piece.png'),
							array('Qrcode', 'fa-qrcode', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-qrcode.png'),
							array('Question', 'fa-question', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-question.png'),
							array('Question sign', 'fa-question-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-question-circle.png'),
							array('Quote left', 'fa-quote-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-quote-left.png'),
							array('Quote right', 'fa-quote-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-quote-right.png'),
							array('Random', 'fa-random', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-random.png'),
							array('Refresh', 'fa-refresh', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-refresh.png'),
							array('Reorder', 'fa-reorder', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-reorder.png'),
							array('Reply', 'fa-reply', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-reply.png'),
							array('Reply all', 'fa-reply-all', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-reply-all.png'),
							array('Resize horizontal', 'fa-resize-horizontal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-horizontal.png'),
							array('Resize vertical', 'fa-resize-vertical', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-vertical.png'),
							array('Retweet', 'fa-retweet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-retweet.png'),
							array('Road', 'fa-road', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-road.png'),
							array('Rocket', 'fa-rocket', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-rocket.png'),
							array('RSS', 'fa-rss', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-rss.png'),
							array('RSS sign', 'fa-rss-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-rss-square.png'),
							array('Search', 'fa-search', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-search.png'),
							array('Share', 'fa-share', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-share.png'),
							array('Share 2', 'fa-share', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-share.png'),
							array('Share sign', 'fa-share-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-share-square.png'),
							array('Shield', 'fa-shield', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-shield.png'),
							array('Shopping cart', 'fa-shopping-cart', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-shopping-cart.png'),
							array('Sign blank', 'fa-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-square.png'),
							array('Signal', 'fa-signal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-signal.png'),
							array('Signin', 'fa-sign-in', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sign-in.png'),
							array('Signout', 'fa-sign-out', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sign-out.png'),
							array('Sitemap', 'fa-sitemap', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sitemap.png'),
							array('Smile', 'fa-smile-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-smile-o.png'),
							array('Sort', 'fa-sort', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort.png'),
							array('Sort by alpha', 'fa-sort-alpha-asc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-alpha-asc.png'),
							array('Sort by alpha 2', 'fa-sort-alpha-desc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-alpha-desc.png'),
							array('Sort by attrib', 'fa-sort-amount-asc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-amount-asc.png'),
							array('Sort by attrib 2', 'fa-sort-amount-desc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-amount-desc.png'),
							array('Sort by order', 'fa-sort-numeric-asc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-numeric-asc.png'),
							array('Sort by order 2', 'fa-sort-numeric-desc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-numeric-desc.png'),
							array('Sort down', 'fa-sort-asc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-asc.png'),
							array('Sort up', 'fa-sort-desc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-desc.png'),
							array('Spinner', 'fa-spinner', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-spinner.png'),
							array('Square', 'fa-square-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-square-o.png'),
							array('Star', 'fa-star', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star.png'),
							array('Star empty', 'fa-star-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star-o.png'),
							array('Star half', 'fa-star-half', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star-half.png'),
							array('Star half empty', 'fa-star-half-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star-half-o.png'),
							array('Subscript', 'fa-subscript', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-subscript.png'),
							array('Suitcase', 'fa-suitcase', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-suitcase.png'),
							array('Sun', 'fa-sun-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sun-o.png'),
							array('Superscript', 'fa-superscript', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-superscript.png'),
							array('Tablet', 'fa-tablet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tablet.png'),
							array('Tachometer', 'fa-tachometer', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tachometer.png'),
							array('Tag', 'fa-tag', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tag.png'),
							array('Tags', 'fa-tags', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tags.png'),
							array('Tasks', 'fa-tasks', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tasks.png'),
							array('Terminal', 'fa-terminal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-terminal.png'),
							array('Thumbs down', 'fa-thumbs-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-down.png'),
							array('Thumbs down 2', 'fa-thumbs-o-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-o-down.png'),
							array('Thumbs up', 'fa-thumbs-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-up.png'),
							array('Thumbs up 2', 'fa-thumbs-o-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-o-up.png'),
							array('Thumb tack', 'fa-thumb-tack', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumb-tack.png'),
							array('Ticket', 'fa-ticket', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ticket.png'),
							array('Times', 'fa-times', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-times.png'),
							array('Times circle', 'fa-times-circle-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-times-circle-o.png'),
							array('Times sign', 'fa-times-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-times-circle.png'),
							array('Tint', 'fa-tint', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tint.png'),
							array('Trash', 'fa-trash-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-trash-o.png'),
							array('Trophy', 'fa-trophy', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-trophy.png'),
							array('Truck', 'fa-truck', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-truck.png'),
							array('Umbrella', 'fa-umbrella', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-umbrella.png'),
							array('Unlock', 'fa-unlock', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-unlock.png'),
							array('Unlock 2', 'fa-unlock-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-unlock-o.png'),
							array('Upload', 'fa-arrow-circle-o-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-o-up.png'),
							array('Upload 2', 'fa-upload', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-upload.png'),
							array('User', 'fa-user', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-user.png'),
							array('Video camera', 'fa-video-camera', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-video-camera.png'),
							array('Volume down', 'fa-volume-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-volume-down.png'),
							array('Volume off', 'fa-volume-off', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-volume-off.png'),
							array('Volume up', 'fa-volume-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-volume-up.png'),
							array('Wrench', 'fa-wrench', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-wrench.png'),
							array('Zoom in', 'fa-search-plus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-search-plus.png'),
							array('Zoom out', 'fa-search-minus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-search-minus.png'),
						array('Text Editor', '--div--'),
							array('Align center', 'fa-align-center', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-center.png'),
							array('Align justify', 'fa-align-justify', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-justify.png'),
							array('Align left', 'fa-align-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-left.png'),
							array('Align right', 'fa-align-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-right.png'),
							array('Bold', 'fa-bold', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bold.png'),
							array('Clipboard', 'fa-clipboard', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-clipboard.png'),
							array('Columns', 'fa-columns', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-columns.png'),
							array('Scissors', 'fa-scissors', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-scissors.png'),
							array('Eraser', 'fa-eraser', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eraser.png'),
							array('File', 'fa-file', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file.png'),
							array('File 2', 'fa-file-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file-o.png'),
							array('File text', 'fa-file-text', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file-text.png'),
							array('File text 2', 'fa-file-text-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file-text-o.png'),
							array('Files', 'fa-files-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-files-o.png'),
							array('Floppy', 'fa-floppy-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-floppy-o.png'),
							array('Font', 'fa-font', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-font.png'),
							array('Indent left', 'fa-outdent', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-outdent.png'),
							array('Indent right', 'fa-indent', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-indent.png'),
							array('Italic', 'fa-italic', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-italic.png'),
							array('Link', 'fa-link', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-link.png'),
							array('List', 'fa-list', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list.png'),
							array('List 2', 'fa-list-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list-alt.png'),
							array('Ordered List', 'fa-list-ol', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list-ol.png'),
							array('Unordered List', 'fa-list-ul', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list-ul.png'),
							array('Paper clip', 'fa-paperclip', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-paperclip.png'),
							array('Repeat', 'fa-repeat', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-repeat.png'),
							array('Strike through', 'fa-strikethrough', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-strikethrough.png'),
							array('Table', 'fa-table', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-table.png'),
							array('Text height', 'fa-text-height', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-text-height.png'),
							array('Text width', 'fa-text-width', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-text-width.png'),
							array('Table header', 'fa-th', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-th.png'),
							array('Table header large', 'fa-th-large', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-th-large.png'),
							array('Table header list', 'fa-th-list', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-th-list.png'),
							array('Underline', 'fa-underline', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-underline.png'),
							array('Undo', 'fa-undo', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-undo.png'),
							array('Unlink', 'fa-chain-broken', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chain-broken.png'),
						array('Directional', '--div--'),
							array('Angle down', 'fa-angle-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-down.png'),
							array('Angle left', 'fa-angle-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-left.png'),
							array('Angle right', 'fa-angle-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-right.png'),
							array('Angle up', 'fa-angle-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-up.png'),
							array('Arrow down', 'fa-arrow-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-down.png'),
							array('Arrow left', 'fa-arrow-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-left.png'),
							array('Arrow right', 'fa-arrow-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-right.png'),
							array('Arrow up', 'fa-arrow-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-up.png'),
							array('Caret down', 'fa-caret-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-down.png'),
							array('Caret left', 'fa-caret-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-left.png'),
							array('Caret right', 'fa-caret-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-right.png'),
							array('Caret up', 'fa-caret-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-up.png'),
							array('Chevron down', 'fa-chevron-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-down.png'),
							array('Chevron left', 'fa-chevron-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-left.png'),
							array('Chevron right', 'fa-chevron-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-right.png'),
							array('Chevron sign down', 'fa-chevron-circle-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-circle-down.png'),
							array('Chevron sign left', 'fa-chevron-circle-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-circle-left.png'),
							array('Chevron sign right', 'fa-chevron-circle-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-circle-right.png'),
							array('Chevron sign up', 'fa-chevron-circle-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-circle-up.png'),
							array('Chevron up', 'fa-chevron-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-up.png'),
							array('Circle arrow down', 'fa-arrow-circle-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-down.png'),
							array('Circle arrow left', 'fa-arrow-circle-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-left.png'),
							array('Circle arrow right', 'fa-arrow-circle-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-right.png'),
							array('Circle arrow up', 'fa-arrow-circle-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-up.png'),
							array('Double angle down', 'fa-angle-double-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-double-down.png'),
							array('Double angle left', 'fa-angle-double-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-double-left.png'),
							array('Double angle right', 'fa-angle-double-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-double-right.png'),
							array('Double angle up', 'fa-angle-double-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-double-up.png'),
							array('Hand down', 'fa-hand-o-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-o-down.png'),
							array('Hand left', 'fa-hand-o-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-o-left.png'),
							array('Hand right', 'fa-hand-o-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-o-right.png'),
							array('Hand up', 'fa-hand-o-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-o-up.png'),
							array('Long arrow down', 'fa-long-arrow-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-down.png'),
							array('Long arrow left', 'fa-long-arrow-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-left.png'),
							array('Long arrow right', 'fa-long-arrow-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-right.png'),
							array('Long arrow up', 'fa-long-arrow-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-up.png'),
						array('Video Player', '--div--'),
							array('Backwards', 'fa-backward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-backward.png'),
							array('Eject', 'fa-eject', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eject.png'),
							array('Fast backwards', 'fa-fast-backward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fast-backward.png'),
							array('Fast forward', 'fa-fast-forward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fast-forward.png'),
							array('Forward', 'fa-forward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-forward.png'),
							array('Fullscreen', 'fa-fullscreen', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fullscreen.png'),
							array('Pause', 'fa-pause', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pause.png'),
							array('Play', 'fa-play', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-play.png'),
							array('Play (circle)', 'fa-play-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-play-circle.png'),
							array('Play (sign)', 'fa-play-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-play-circle.png'),
							array('Resize full', 'fa-resize-full', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-full.png'),
							array('Resize small', 'fa-resize-small', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-small.png'),
							array('Step backward', 'fa-step-backward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-step-backward.png'),
							array('Step forward', 'fa-step-forward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-step-forward.png'),
							array('Stop', 'fa-stop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-stop.png'),
							array('Youtube play', 'fa-youtube-play', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube-play.png'),
						array('Currencies', '--div--'),
							array('Euro', 'fa-eur', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eur.png'),
							array('US Dollar', 'fa-usd', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-usd.png'),
							array('UK Pounds', 'fa-gbp', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gbp.png'),
							array('Japan Yen', 'fa-jpy', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-jpy.png'),
							array('Chinese Reminbi', 'fa-cny', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cny.png'),
							array('India Rubee', 'fa-inr', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-inr.png'),
							array('Korea Won', 'fa-krw', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-krw.png'),
							array('Bitcoin', 'fa-btc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-btc.png'),
						array('Brand', '--div--'),
							array('Adn', 'fa-adn', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-adn.png'),
							array('Android', 'fa-android', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-android.png'),
							array('Apple', 'fa-apple', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-apple.png'),
							array('Bitbucket', 'fa-bitbucket', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bitbucket.png'),
							array('Bitbucket sign', 'fa-bitbucket-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bitbucket-square.png'),
							array('CSS3', 'fa-css3', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-css3.png'),
							array('Dribble', 'fa-dribbble', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-dribbble.png'),
							array('Dropbox', 'fa-dropbox', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-dropbox.png'),
							array('Facebook', 'fa-facebook', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-facebook.png'),
							array('Facebook sign', 'fa-facebook-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-facebook-square.png'),
							array('Flickr', 'fa-flickr', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flickr.png'),
							array('Foursquare', 'fa-foursquare', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-foursquare.png'),
							array('Github', 'fa-github', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-github.png'),
							array('Github 2', 'fa-github-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-github-alt.png'),
							array('Github sign', 'fa-github-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-github-square.png'),
							array('GitTip', 'fa-gittip', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gittip.png'),
							array('Google+', 'fa-google-plus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-google-plus.png'),
							array('Google+ sign', 'fa-google-plus-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-google-plus-square.png'),
							array('HTML5', 'fa-html5', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-html5.png'),
							array('Instagram', 'fa-instagram', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-instagram.png'),
							array('LinkedIn', 'fa-linkedin', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-linkedin.png'),
							array('LinkedIn sign', 'fa-linkedin-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-linkedin-square.png'),
							array('Linux', 'fa-linux', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-linux.png'),
							array('MaxCDN', 'fa-maxcdn', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-maxcdn.png'),
							array('Pinterest', 'fa-pinterest', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pinterest.png'),
							array('Pinterest sign', 'fa-pinterest-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pinterest-square.png'),
							array('Renren', 'fa-renren'),
							array('Skype', 'fa-skype', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-skype.png'),
							array('StackExchange', 'fa-stackexchange', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-stackexchange.png'),
							array('Trello', 'fa-trello', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-trello.png'),
							array('Tumblr', 'fa-tumblr', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tumblr.png'),
							array('Tumblr sign', 'fa-tumblr-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tumblr-square.png'),
							array('Twitter', 'fa-twitter', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-twitter.png'),
							array('Twitter sign', 'fa-twitter-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-twitter-square.png'),
							array('VK', 'fa-vk', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-vk.png'),
							array('Weibo', 'fa-weibo', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-weibo.png'),
							array('Windows', 'fa-windows', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-windows.png'),
							array('Xing', 'fa-xing', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-xing.png'),
							array('Xing sign', 'fa-xing-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-xing-square.png'),
							array('YouTube', 'fa-youtube', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube.png'),
							array('YouTube play', 'fa-youtube-play', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube-play.png'),
							array('YouTube sign', 'fa-youtube-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube-square.png'),
						array('Medical', '--div--'),
							array('Ambulance', 'fa-ambulance', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ambulance.png'),
							array('H-Square', 'fa-h-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-h-square.png'),
							array('Hospital', 'fa-hospital', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hospital.png'),
							array('MedKit', 'fa-medkit', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-medkit.png'),
							array('Stethoscope', 'fa-stethoscope', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-stethoscope.png'),
							array('User MD', 'fa-user-md', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-user-md.png')
);

?>