<?php

// Font Awesome Icons v3.2.1
//
$iconFontOption = array(array('', '0'),
						array('Web Application', '--div--'),
							array('Adjust', 'adjust', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-adjust.png'),
							array('Anchor', 'anchor', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-anchor.png'),
							array('Archive', 'archive', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-archive.png'),
							array('Arrow circle down', 'arrow-circle-o-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-o-down.png'),
							array('Asterisk', 'asterisk', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-asterisk.png'),
							array('Ban circle', 'ban', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ban.png'),
							array('Bar chart', 'bar-chart-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bar-chart-o.png'),
							array('Barcode', 'barcode', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-barcode.png'),
							array('Beaker', 'flask', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flask.png'),
							array('Beer', 'beer', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-beer.png'),
							array('Bell', 'bell-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bell-o.png'),
							array('Bell 2', 'bell', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bell.png'),
							array('Bolt', 'bolt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bolt.png'),
							array('Book', 'book', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-book.png'),
							array('Bookmark', 'bookmark', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bookmark.png'),
							array('Bookmark empty', 'bookmark-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bookmark-o.png'),
							array('Briefcase', 'briefcase', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-briefcase.png'),
							array('Bug', 'bug', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bug.png'),
							array('Building', 'building', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-building.png'),
							array('Bullhorn', 'bullhorn', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bullhorn.png'),
							array('Bullseye', 'bullseye', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bullseye.png'),
							array('Calendar', 'calendar', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-calendar.png'),
							array('Calendar empty', 'calendar-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-calendar-o.png'),
							array('Camera', 'camera', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-camera.png'),
							array('Camera-retro', 'camera-retro', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-camera-retro.png'),
							array('Caret square down', 'caret-square-o-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-square-o-down.png'),
							array('Caret square up', 'caret-square-o-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-square-o-up.png'),
							array('Certificate', 'certificate', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-certificate.png'),
							array('Check', 'check-square-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check-square-o.png'),
							array('Check', 'check', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check.png'),
							array('Check circle', 'check-circle-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check-circle-o.png'),
							array('Check sign', 'check-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check-circle.png'),
							array('Check sign', 'check-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-check-square.png'),
							array('Circle', 'circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-circle.png'),
							array('Circle blank', 'circle-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-circle-o.png'),
							array('Clock', 'clock-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-clock-o.png'),
							array('Cloud', 'cloud', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cloud.png'),
							array('Cloud download', 'cloud-download', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cloud-download.png'),
							array('Cloud upload', 'cloud-upload', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cloud-upload.png'),
							array('Code', 'code', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-code.png'),
							array('Code fork', 'code-fork', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-code-fork.png'),
							array('Coffee', 'coffee', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-coffee.png'),
							array('Cog', 'cog', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cog.png'),
							array('Cogs', 'cogs', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cogs.png'),
							array('Collapse', 'collapse-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-collapse-o.png'),
							array('Comment', 'comment', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comment.png'),
							array('Comment 2', 'comment-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comment-o.png'),
							array('Comments', 'comments', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comments.png'),
							array('Comments 2', 'comments-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-comments-o.png'),
							array('Compass', 'compass', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-compass.png'),
							array('Credit card', 'credit-card', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-credit-card.png'),
							array('Crop', 'crop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-crop.png'),
							array('Crosshairs', 'crosshairs', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-crosshairs.png'),
							array('Cutlery', 'cutlery', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cutlery.png'),
							array('Desktop', 'desktop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-desktop.png'),
							array('Download', 'download', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-download.png'),
							array('Ellipsis horizontal', 'ellipsis-horizontal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ellipsis-horizontal.png'),
							array('Ellipsis vertical', 'ellipsis-vertical', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ellipsis-vertical.png'),
							array('Envelope', 'envelope', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-envelope.png'),
							array('Envelope-alt', 'envelope-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-envelope-o.png'),
							array('Eraser', 'eraser', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eraser.png'),
							array('Exchange', 'exchange', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-exchange.png'),
							array('Exclamation', 'exclamation', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-exclamation.png'),
							array('Exclamation sign', 'exclamation-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-exclamation-circle.png'),
							array('Exclamation triangle', 'exclamation-triangle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-exclamation-triangle.png'),
							array('Expand', 'caret-square-o-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-square-o-right.png'),
							array('Expand-alt', 'expand-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-expand-o.png'),
							array('External link', 'external-link', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-external-link.png'),
							array('External link sign', 'external-link-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-external-link-square.png'),
							array('Eye close', 'eye-slash', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eye-slash.png'),
							array('Eye', 'eye', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eye.png'),
							array('Female', 'female', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-female.png'),
							array('Fighter jet', 'fighter-jet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fighter-jet.png'),
							array('Film', 'film', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-film.png'),
							array('Filter', 'filter', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-filter.png'),
							array('Fire', 'fire', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fire.png'),
							array('Fire extinguisher', 'fire-extinguisher', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fire-extinguisher.png'),
							array('Flag', 'flag', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flag.png'),
							array('Flag 2', 'flag-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flag-o.png'),
							array('Flag', 'flag-checkered', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flag-checkered.png'),
							array('Folder close', 'folder', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder.png'),
							array('Folder close 2', 'folder-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder-o.png'),
							array('Folder open', 'folder-open', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder-open.png'),
							array('Folder open 2', 'folder-open-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-folder-open-o.png'),
							array('Frown', 'frown-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-frown-o.png'),
							array('Gamepad', 'gamepad', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gamepad.png'),
							array('Gift', 'gift', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gift.png'),
							array('Glass', 'glass', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-glass.png'),
							array('Globe', 'globe', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-globe.png'),
							array('Group', 'group', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-group.png'),
							array('HDD', 'hdd-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hdd-o.png'),
							array('Headphones', 'headphones', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-headphones.png'),
							array('Heart', 'heart', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-heart.png'),
							array('Heart empty', 'heart-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-heart-o.png'),
							array('Home', 'home', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-home.png'),
							array('Inbox', 'inbox', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-inbox.png'),
							array('Info', 'info', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-info.png'),
							array('Info sign', 'info-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-info-circle.png'),
							array('Key', 'key', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-key.png'),
							array('Keyboard', 'keyboard-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-keyboard-o.png'),
							array('Laptop', 'laptop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-laptop.png'),
							array('Leaf', 'leaf', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-leaf.png'),
							array('Legal', 'gavel', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gavel.png'),
							array('Lemon', 'lemon-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-lemon-o.png'),
							array('Level down', 'level-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-level-down.png'),
							array('Level up', 'level-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-level-up.png'),
							array('Lightbulb', 'lightbulb-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-lightbulb-o.png'),
							array('Location arrow', 'location-arrow', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-location-arrow.png'),
							array('Lock', 'lock', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-lock.png'),
							array('Magic', 'magic', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-magic.png'),
							array('Magnet', 'magnet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-magnet.png'),
							array('Mail reply all', 'mail-reply-all', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-mail-reply-all.png'),
							array('Male', 'male', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-male.png'),
							array('Map marker', 'map-marker', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-map-marker.png'),
							array('Meh', 'meh-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-meh-o.png'),
							array('Microphone', 'microphone', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-microphone.png'),
							array('Microphone slash', 'microphone-slash', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-microphone-slash.png'),
							array('Minus', 'minus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-minus.png'),
							array('Minus square', 'minus-square-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-minus-square-o.png'),
							array('Minus sign', 'minus-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-minus-circle.png'),
							array('Minus sign 2', 'minus-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-minus-square.png'),
							array('Mobile', 'mobile', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-mobile.png'),
							array('Money', 'money', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-money.png'),
							array('Moon', 'moon-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-moon-o.png'),
							array('Move', 'move', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-move.png'),
							array('Music', 'music', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-music.png'),
							array('Pencil', 'pencil', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pencil.png'),
							array('Pencil', 'pencil-square-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pencil-square-o.png'),
							array('Pencil square', 'pencil-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pencil-square.png'),
							array('Phone', 'phone', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-phone.png'),
							array('Phone sign', 'phone-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-phone-square.png'),
							array('Picture', 'picture-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-picture-o.png'),
							array('Plane', 'plane', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plane.png'),
							array('Plus', 'plus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plus.png'),
							array('Plus sign', 'plus-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plus-circle.png'),
							array('Plus sign 2', 'plus-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-plus-square.png'),
							array('Power off', 'power-off', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-power-off.png'),
							array('Print', 'print', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-print.png'),
							array('Puzzle piece', 'puzzle-piece', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-puzzle-piece.png'),
							array('Qrcode', 'qrcode', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-qrcode.png'),
							array('Question', 'question', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-question.png'),
							array('Question sign', 'question-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-question-circle.png'),
							array('Quote left', 'quote-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-quote-left.png'),
							array('Quote right', 'quote-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-quote-right.png'),
							array('Random', 'random', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-random.png'),
							array('Refresh', 'refresh', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-refresh.png'),
							array('Reorder', 'reorder', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-reorder.png'),
							array('Reply', 'reply', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-reply.png'),
							array('Reply all', 'reply-all', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-reply-all.png'),
							array('Resize horizontal', 'resize-horizontal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-horizontal.png'),
							array('Resize vertical', 'resize-vertical', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-vertical.png'),
							array('Retweet', 'retweet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-retweet.png'),
							array('Road', 'road', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-road.png'),
							array('Rocket', 'rocket', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-rocket.png'),
							array('RSS', 'rss', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-rss.png'),
							array('RSS sign', 'rss-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-rss-square.png'),
							array('Search', 'search', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-search.png'),
							array('Share', 'share', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-share.png'),
							array('Share 2', 'share', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-share.png'),
							array('Share sign', 'share-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-share-square.png'),
							array('Shield', 'shield', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-shield.png'),
							array('Shopping cart', 'shopping-cart', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-shopping-cart.png'),
							array('Sign blank', 'square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-square.png'),
							array('Signal', 'signal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-signal.png'),
							array('Signin', 'sign-in', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sign-in.png'),
							array('Signout', 'sign-out', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sign-out.png'),
							array('Sitemap', 'sitemap', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sitemap.png'),
							array('Smile', 'smile-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-smile-o.png'),
							array('Sort', 'sort', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort.png'),
							array('Sort by alpha', 'sort-alpha-asc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-alpha-asc.png'),
							array('Sort by alpha 2', 'sort-alpha-desc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-alpha-desc.png'),
							array('Sort by attrib', 'sort-amount-asc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-amount-asc.png'),
							array('Sort by attrib 2', 'sort-amount-desc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-amount-desc.png'),
							array('Sort by order', 'sort-numeric-asc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-numeric-asc.png'),
							array('Sort by order 2', 'sort-numeric-desc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-numeric-desc.png'),
							array('Sort down', 'sort-asc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-asc.png'),
							array('Sort up', 'sort-desc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sort-desc.png'),
							array('Spinner', 'spinner', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-spinner.png'),
							array('Square', 'square-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-square-o.png'),
							array('Star', 'star', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star.png'),
							array('Star empty', 'star-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star-o.png'),
							array('Star half', 'star-half', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star-half.png'),
							array('Star half empty', 'star-half-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-star-half-o.png'),
							array('Subscript', 'subscript', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-subscript.png'),
							array('Suitcase', 'suitcase', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-suitcase.png'),
							array('Sun', 'sun-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-sun-o.png'),
							array('Superscript', 'superscript', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-superscript.png'),
							array('Tablet', 'tablet', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tablet.png'),
							array('Tachometer', 'tachometer', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tachometer.png'),
							array('Tag', 'tag', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tag.png'),
							array('Tags', 'tags', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tags.png'),
							array('Tasks', 'tasks', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tasks.png'),
							array('Terminal', 'terminal', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-terminal.png'),
							array('Thumbs down', 'thumbs-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-down.png'),
							array('Thumbs down 2', 'thumbs-o-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-o-down.png'),
							array('Thumbs up', 'thumbs-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-up.png'),
							array('Thumbs up 2', 'thumbs-o-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumbs-o-up.png'),
							array('Thumb tack', 'thumb-tack', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-thumb-tack.png'),
							array('Ticket', 'ticket', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ticket.png'),
							array('Times', 'times', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-times.png'),
							array('Times circle', 'times-circle-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-times-circle-o.png'),
							array('Times sign', 'times-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-times-circle.png'),
							array('Tint', 'tint', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tint.png'),
							array('Trash', 'trash-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-trash-o.png'),
							array('Trophy', 'trophy', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-trophy.png'),
							array('Truck', 'truck', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-truck.png'),
							array('Umbrella', 'umbrella', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-umbrella.png'),
							array('Unlock', 'unlock', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-unlock.png'),
							array('Unlock 2', 'unlock-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-unlock-o.png'),
							array('Upload', 'arrow-circle-o-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-o-up.png'),
							array('Upload 2', 'upload', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-upload.png'),
							array('User', 'user', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-user.png'),
							array('Video camera', 'video-camera', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-video-camera.png'),
							array('Volume down', 'volume-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-volume-down.png'),
							array('Volume off', 'volume-off', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-volume-off.png'),
							array('Volume up', 'volume-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-volume-up.png'),
							array('Wrench', 'wrench', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-wrench.png'),
							array('Zoom in', 'search-plus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-search-plus.png'),
							array('Zoom out', 'search-minus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-search-minus.png'),
						array('Text Editor', '--div--'),
							array('Align center', 'align-center', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-center.png'),
							array('Align justify', 'align-justify', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-justify.png'),
							array('Align left', 'align-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-left.png'),
							array('Align right', 'align-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-align-right.png'),
							array('Bold', 'bold', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bold.png'),
							array('Clipboard', 'clipboard', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-clipboard.png'),
							array('Columns', 'columns', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-columns.png'),
							array('Scissors', 'scissors', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-scissors.png'),
							array('Eraser', 'eraser', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eraser.png'),
							array('File', 'file', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file.png'),
							array('File 2', 'file-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file-o.png'),
							array('File text', 'file-text', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file-text.png'),
							array('File text 2', 'file-text-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-file-text-o.png'),
							array('Files', 'files-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-files-o.png'),
							array('Floppy', 'floppy-o', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-floppy-o.png'),
							array('Font', 'font', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-font.png'),
							array('Indent left', 'outdent', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-outdent.png'),
							array('Indent right', 'indent', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-indent.png'),
							array('Italic', 'italic', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-italic.png'),
							array('Link', 'link', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-link.png'),
							array('List', 'list', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list.png'),
							array('List 2', 'list-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list-alt.png'),
							array('Ordered List', 'list-ol', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list-ol.png'),
							array('Unordered List', 'list-ul', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-list-ul.png'),
							array('Paper clip', 'paperclip', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-paperclip.png'),
							array('Repeat', 'repeat', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-repeat.png'),
							array('Strike through', 'strikethrough', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-strikethrough.png'),
							array('Table', 'table', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-table.png'),
							array('Text height', 'text-height', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-text-height.png'),
							array('Text width', 'text-width', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-text-width.png'),
							array('Table header', 'th', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-th.png'),
							array('Table header large', 'th-large', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-th-large.png'),
							array('Table header list', 'th-list', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-th-list.png'),
							array('Underline', 'underline', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-underline.png'),
							array('Undo', 'undo', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-undo.png'),
							array('Unlink', 'chain-broken', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chain-broken.png'),
						array('Directional', '--div--'),
							array('Angle down', 'angle-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-down.png'),
							array('Angle left', 'angle-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-left.png'),
							array('Angle right', 'angle-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-right.png'),
							array('Angle up', 'angle-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-up.png'),
							array('Arrow down', 'arrow-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-down.png'),
							array('Arrow left', 'arrow-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-left.png'),
							array('Arrow right', 'arrow-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-right.png'),
							array('Arrow up', 'arrow-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-up.png'),
							array('Caret down', 'caret-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-down.png'),
							array('Caret left', 'caret-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-left.png'),
							array('Caret right', 'caret-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-right.png'),
							array('Caret up', 'caret-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-caret-up.png'),
							array('Chevron down', 'chevron-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-down.png'),
							array('Chevron left', 'chevron-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-left.png'),
							array('Chevron right', 'chevron-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-right.png'),
							array('Chevron sign down', 'chevron-circle-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-circle-down.png'),
							array('Chevron sign left', 'chevron-circle-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-circle-left.png'),
							array('Chevron sign right', 'chevron-circle-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-circle-right.png'),
							array('Chevron sign up', 'chevron-circle-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-circle-up.png'),
							array('Chevron up', 'chevron-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-chevron-up.png'),
							array('Circle arrow down', 'arrow-circle-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-down.png'),
							array('Circle arrow left', 'arrow-circle-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-left.png'),
							array('Circle arrow right', 'arrow-circle-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-right.png'),
							array('Circle arrow up', 'arrow-circle-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-arrow-circle-up.png'),
							array('Double angle down', 'angle-double-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-double-down.png'),
							array('Double angle left', 'angle-double-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-double-left.png'),
							array('Double angle right', 'angle-double-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-double-right.png'),
							array('Double angle up', 'angle-double-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-angle-double-up.png'),
							array('Hand down', 'hand-o-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-o-down.png'),
							array('Hand left', 'hand-o-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-o-left.png'),
							array('Hand right', 'hand-o-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-o-right.png'),
							array('Hand up', 'hand-o-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hand-o-up.png'),
							array('Long arrow down', 'long-arrow-down', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-down.png'),
							array('Long arrow left', 'long-arrow-left', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-left.png'),
							array('Long arrow right', 'long-arrow-right', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-right.png'),
							array('Long arrow up', 'long-arrow-up', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-long-arrow-up.png'),
						array('Video Player', '--div--'),
							array('Backwards', 'backward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-backward.png'),
							array('Eject', 'eject', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eject.png'),
							array('Fast backwards', 'fast-backward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fast-backward.png'),
							array('Fast forward', 'fast-forward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fast-forward.png'),
							array('Forward', 'forward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-forward.png'),
							array('Fullscreen', 'fullscreen', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-fullscreen.png'),
							array('Pause', 'pause', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pause.png'),
							array('Play', 'play', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-play.png'),
							array('Play (circle)', 'play-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-play-circle.png'),
							array('Play (sign)', 'play-circle', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-play-circle.png'),
							array('Resize full', 'resize-full', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-full.png'),
							array('Resize small', 'resize-small', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-resize-small.png'),
							array('Step backward', 'step-backward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-step-backward.png'),
							array('Step forward', 'step-forward', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-step-forward.png'),
							array('Stop', 'stop', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-stop.png'),
							array('Youtube play', 'youtube-play', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube-play.png'),
						array('Currencies', '--div--'),
							array('Euro', 'eur', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-eur.png'),
							array('US Dollar', 'usd', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-usd.png'),
							array('UK Pounds', 'gbp', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gbp.png'),
							array('Japan Yen', 'jpy', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-jpy.png'),
							array('Chinese Reminbi', 'cny', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-cny.png'),
							array('India Rubee', 'inr', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-inr.png'),
							array('Korea Won', 'krw', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-krw.png'),
							array('Bitcoin', 'btc', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-btc.png'),
						array('Brand', '--div--'),
							array('Adn', 'adn', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-adn.png'),
							array('Android', 'android', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-android.png'),
							array('Apple', 'apple', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-apple.png'),
							array('Bitbucket', 'bitbucket', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bitbucket.png'),
							array('Bitbucket sign', 'bitbucket-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-bitbucket-square.png'),
							array('CSS3', 'css3', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-css3.png'),
							array('Dribble', 'dribbble', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-dribbble.png'),
							array('Dropbox', 'dropbox', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-dropbox.png'),
							array('Facebook', 'facebook', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-facebook.png'),
							array('Facebook sign', 'facebook-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-facebook-square.png'),
							array('Flickr', 'flickr', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-flickr.png'),
							array('Foursquare', 'foursquare', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-foursquare.png'),
							array('Github', 'github', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-github.png'),
							array('Github 2', 'github-alt', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-github-alt.png'),
							array('Github sign', 'github-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-github-square.png'),
							array('GitTip', 'gittip', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-gittip.png'),
							array('Google+', 'google-plus', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-google-plus.png'),
							array('Google+ sign', 'google-plus-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-google-plus-square.png'),
							array('HTML5', 'html5', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-html5.png'),
							array('Instagram', 'instagram', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-instagram.png'),
							array('LinkedIn', 'linkedin', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-linkedin.png'),
							array('LinkedIn sign', 'linkedin-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-linkedin-square.png'),
							array('Linux', 'linux', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-linux.png'),
							array('MaxCDN', 'maxcdn', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-maxcdn.png'),
							array('Pinterest', 'pinterest', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pinterest.png'),
							array('Pinterest sign', 'pinterest-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-pinterest-square.png'),
							array('Renren', 'renren'),
							array('Skype', 'skype', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-skype.png'),
							array('StackExchange', 'stackexchange', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-stackexchange.png'),
							array('Trello', 'trello', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-trello.png'),
							array('Tumblr', 'tumblr', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tumblr.png'),
							array('Tumblr sign', 'tumblr-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-tumblr-square.png'),
							array('Twitter', 'twitter', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-twitter.png'),
							array('Twitter sign', 'twitter-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-twitter-square.png'),
							array('VK', 'vk', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-vk.png'),
							array('Weibo', 'weibo', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-weibo.png'),
							array('Windows', 'windows', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-windows.png'),
							array('Xing', 'xing', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-xing.png'),
							array('Xing sign', 'xing-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-xing-square.png'),
							array('YouTube', 'youtube', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube.png'),
							array('YouTube play', 'youtube-play', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube-play.png'),
							array('YouTube sign', 'youtube-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-youtube-square.png'),
						array('Medical', '--div--'),
							array('Ambulance', 'ambulance', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-ambulance.png'),
							array('H-Square', 'h-square', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-h-square.png'),
							array('Hospital', 'hospital', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-hospital.png'),
							array('MedKit', 'medkit', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-medkit.png'),
							array('Stethoscope', 'stethoscope', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-stethoscope.png'),
							array('User MD', 'user-md', 'EXT:bootstrap_core/Resources/Public/Icons/fawesome/icon-user-md.png')
);

?>